myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import homepage,about
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", homepage),
    path("about/",about),
    path("posts/", include('posts.urls')),
    path("users/", include('users.urls')),
    
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from .views import posts_lists,post_page,post_new

app_name = 'posts'

urlpatterns = [
    path("", posts_lists, name="list"),
    path("new-post/", post_new, name="new-post"),
    path("<slug:slug>", post_page, name="page"),
    
]

myproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("register/",views.register_view , name="register"),
    path("login/",views.login_view , name="login"),
    path("logout/",views.logout_view , name="logout"),
    
    
    
]

myproject/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()  
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png',blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

myproject/users/models.py
from django.db import models

# Create your models here.

myproject/posts/forms.py
from django import forms
from . import models 

class CreatePost(forms.ModelForm):
    class Meta:
        model: models.Post
        fields: ['title', 'body','slug','banner']
            

myproject/myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render
# def homepage(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

# def about(request):
#     return HttpResponse("This is the about page")
    


def homepage(request):
    return render(request,'home.html')

def about(request):
     return render(request,'about.html')
    

myproject/posts/views.py
from django.shortcuts import render,redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def posts_lists(request):
    post = Post.objects.all().order_by('-date')
    return render(request, 'posts/post_list.html', {'posts':post})

def post_page(request, slug):
 post = Post.objects.get(slug=slug)
 return render(request, 'posts/post_page.html', {'post':post})

@login_required(login_url="/users/login/")
def  post_new(request):
    if request.method == "POST":
        form = forms.CreatePost(request.POST, request.FILES)   
        if form.is_valid():
            return redirect('posts:list') 
        
    else:
        form = forms.CreatePost()
        
    return render(request, "posts/post_new.html")

myproject/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login,logout
# Create your views here.
def register_view(request):
    if request.method == "POST":
     form = UserCreationForm(request.POST)
     print(request.method)
     print(form.is_valid())
     print(form.fields.values())
     if form.is_valid():
      print(form.is_valid())
      auth_login(request,form.get_user())
      return redirect("posts:list")
    else:
     form = UserCreationForm()

    return render(request, 'users/register.html',  {"form":form})

def login_view(request):
    if request.method == 'POST':
     form = AuthenticationForm(data=request.POST)
     if form.is_valid():
      print(form.is_valid())
      return redirect("posts:list")
    else:
        form = AuthenticationForm()
        
    return render(request,'users/login.html', {"form":form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("users:login")

myproject/posts/templates/posts/post_list.html
{%  extends 'layout.html' %}

{% block title %}
 Posts Lists
{% endblock %}


{% block content %}

<section>
    <h1>Posts</h1>
{% for post in posts %}
<article>
    <h2>{{post.title}}</h2>
    <p>{{post.body}}</p>
    <p>{{post.date}}</p>
</article>
{% endfor %}
</section>
{% endblock %}%}

myproject/posts/templates/posts/post_new.html
{%  extends 'layout.html' %}

{% block title %}
 New Post Page
{% endblock %}


{% block content %}
<section>
    <h1>New Post</h1>

    <form action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
        {% csrf_token%}
{{form}}
<button>Submit</button>
    </form>

</section>
{% endblock %}

myproject/posts/templates/posts/post_page.html
{%  extends 'layout.html' %}

{% block title %}
 Posts Lists
{% endblock %}


{% block content %}

<section>
    <h1>Post Detail</h1>
    <h2>
       
        {{post.title}}
    </h2>
    <img  src="{{post.banner.url}}" alt="some"/>
    <p>{{post.body}}</p>
    <p>{{post.date}}</p>
</section>
{% endblock %}

myproject/templates/about.html
{% extends 'layout.html'%}

{% block title %}
 Home
{% endblock %}


{% block content %}

<h1>About</h1>
<p>Check out my <a href="/">Home </a>page</p>
{% endblock %}%}

myproject/templates/home.html
{%  extends 'layout.html' %}

{% block title %}
 Home
{% endblock %}


{% block content %}
<h1>Home</h1>
<p>Check out my <a href="/about">About </a>page</p>
{% endblock %}%}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            {% block title%}
              Django App
            {%  endblock %}
        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />


    </head>
    <body>

        <nav>
            <a href="/" >Home🏠</a> | 
            <a href="/about" >About 😃</a> | 
            <a href="{% url 'posts:list' %}" >News 📰</a> | 
            <a href="{% url 'users:register' %}" >🚀</a> | 
            <a href="{% url 'users:login' %}" >🔏</a> | 
            {% if user.is_authenticated%}
            <a href="{% url 'posts:new-post' %}" >🆕</a> | 
            {%  endif %}
           
            <form actions="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button >
👋
                </button>
            </form>


        </nav>

        <main>
            {% block content%}

            {% endblock%}
        </main>
        
        <script src="" async defer></script>
    </body>
</html>

myproject/users/templates/users/login.html
{%  extends 'layout.html' %}

{% block title %}
 Login User
{% endblock %}


{% block content %}

<section>
    <h1>Login User</h1>
    <form action="/users/login/" method="post">
        {% csrf_token %}
{{form}}
<button>Submit</button>
    </form>
   
</section>
{% endblock %}

myproject/users/templates/users/register.html
{%  extends 'layout.html' %}

{% block title %}
 Register a New User
{% endblock %}


{% block content %}

<section>
    <h1>Register a New User</h1>
    <form action="/users/register/" method="post">
        {% csrf_token %}
{{form}}
<button>Submit</button>
    </form>
   
</section>
{% endblock %}